"groups":
- "name": "karpenter"
  "rules":
  - "alert": "KarpenterCloudProviderErrors"
    "annotations":
      "dashboard_url": "https://grafana.devops.bestegg.com/d/kubernetes-autoscaling-mixin-kperf-jkwq/kubernetes-autoscaling-karpenter-performance&var-cluster={{ $labels.cluster }}"
      "description": "The Karpenter provider {{ $labels.provider }} with the controller {{ $labels.controller }} has errors with the method {{ $labels.method }}."
      "summary": "Karpenter has Cloud Provider Errors."
    "expr": |
      sum(
        increase(
          karpenter_cloudprovider_errors_total{
            job="karpenter",
            controller!~"nodeclaim.termination|node.termination",
            error!="NodeClaimNotFoundError"
          }[5m]
        )
      ) by (cluster, namespace, job, provider, controller, method) > 0
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "KarpenterNodeClaimsTerminationDurationHigh"
    "annotations":
      "dashboard_url": "https://grafana.devops.bestegg.com/d/kubernetes-autoscaling-mixin-kact-jkwq/kubernetes-autoscaling-karpenter-activity&var-cluster={{ $labels.cluster }}"
      "description": "The average node claim termination duration in Karpenter has exceeded 20 minutes for more than 15 minutes in nodepool {{ $labels.nodepool }}. This may indicate cloud provider issues or improper instance termination handling."
      "summary": "Karpenter Node Claims Termination Duration is High."
    "expr": |
      sum(
        karpenter_nodeclaims_termination_duration_seconds_sum{
          job="karpenter"
        }
      ) by (cluster, namespace, job, nodepool)
      /
      sum(
        karpenter_nodeclaims_termination_duration_seconds_count{
          job="karpenter"
        }
      ) by (cluster, namespace, job, nodepool) > 1200
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "KarpenterNodepoolNearCapacity"
    "annotations":
      "dashboard_url": "https://grafana.devops.bestegg.com/d/kubernetes-autoscaling-mixin-kover-jkwq/kubernetes-autoscaling-karpenter-overview&var-cluster={{ $labels.cluster }}"
      "description": "The resource {{ $labels.resource_type }} in the Karpenter node pool {{ $labels.nodepool }} is nearing its limit. Consider scaling or adding resources."
      "summary": "Karpenter Nodepool near capacity."
    "expr": |
      sum (
        karpenter_nodepools_usage{job="karpenter"}
      ) by (cluster, namespace, job, nodepool, resource_type)
      /
      sum (
        karpenter_nodepools_limit{job="karpenter"}
      ) by (cluster, namespace, job, nodepool, resource_type)
      * 100 > 75
    "for": "15m"
    "labels":
      "severity": "warning"
