"groups":
- "name": "karpenter"
  "rules":
  - "alert": "KarpenterCloudProviderErrors"
    "annotations":
      "dashboard_url": "https://grafana.com/d/kubernetes-autoscaling-mixin-kperf-jkwq/kubernetes-autoscaling-karpenter-performance"
      "description": "The Karpenter provider {{ $labels.provider }} with the controller {{ $labels.controller }} has errors with the method {{ $labels.method }}."
      "summary": "Karpenter has Cloud Provider Errors."
    "expr": |
      sum(
        increase(
          karpenter_cloudprovider_errors_total{
            job=~"karpenter"
          }[5m]
        )
      ) by (namespace, job, provider, controller, method) > 0
    "for": "5m"
    "labels":
      "severity": "warning"
